server:
  servlet:
    context-path: /api
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fitmarket?serverTimezone=UTC
    username: ssafy
    password: ssafy
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: -1ms
  cache:
    type: redis
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

logging:
  level:
    com.ssafy.fitmarket_be: info

mybatis:
  type-aliases-package: com.ssafy.fitmarket_be
  mapper-locations: classpath:/mappers/**/*.xml

jwt:
  access-expiration-time: 900000
  refresh-expiration-time: 604800000
  secret: YXNkc2FmZGFzZmFzZGZhZHNmYWRzZmFzZGFzZmFzZGYxMjM=

# 파일 업로드 설정
file:
  upload-dir: uploads