server:
  servlet:
    context-path: /api

spring:
  application:
    name: fitmarket
  profiles:
    active: dev
  ai:
    openai:
      base-url: "dev-url"
      api-key: "mock-api-key"
      chat:
        options:
          model: "mock-model"
          temperature: 0.3
      embedding:
        options:
          model: "mock-embedding-model"

logging:
  pattern:
    console: "%d{HH:mm:ss} [%level] %c{36} %m%n"
  level:
    org.springframework.ai: DEBUG
    org.springframework.web.client: DEBUG

#mybatis:
#  type-aliases-package: com.ssafy.fitmarket_be.dto
#  mapper-locations: classpath:/mappers/**/*.xml

app:
  ai:
    enabled: false  # true로 변경하면 AI 식품 매칭 활성화

cors:
  allowed-origins: http://localhost:5173